<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow">
    <title>@yield('title', 'Something went wrong') - ShopPilot</title>
    <link rel="icon" href="{{ asset('favicon.ico') }}">
    <link rel="stylesheet" href="{{ asset('assets/website/vendor/fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/website/css/error-pages.css') }}">
</head>
<body>
    <div class="error-topbar"><div class="error-container error-topbar-inner"><div class="error-benefits"><span><i class="fas fa-truck"></i> Free delivery on orders over ৳1,000</span><span><i class="fas fa-lock"></i> Secure Payment</span><span><i class="fas fa-undo-alt"></i> Easy Returns</span><span><i class="fas fa-headset"></i> 24/7 Support</span></div><div class="error-top-links"><a href="/track-order">Track Order</a><span>|</span><a href="/contact">Help &amp; Support</a></div></div></div>
    <header class="error-header"><div class="error-container error-header-inner"><a href="/" class="error-brand"><span class="error-brand-mark"><i class="fas fa-shopping-bag"></i></span><span class="error-brand-copy"><strong>Shop<span>Pilot</span></strong><small>Shop Smart. Live Better</small></span></a><form class="error-search" action="/shop" method="GET"><input type="search" name="q" placeholder="Search for products, categories..." aria-label="Search products"><button type="submit" aria-label="Search"><i class="fas fa-search"></i></button></form><nav class="error-header-actions"><a href="/"><i class="fas fa-home"></i><span>Home</span></a><a href="/shop"><i class="fas fa-shopping-bag"></i><span>Shop</span></a></nav></div></header>
    <main class="error-main"><div class="error-container"><section class="error-card"><div class="error-visual" aria-hidden="true"><div class="error-code-shadow">@yield('code', 'Error')</div><div class="error-bag"><i class="fas @yield('icon', 'fa-shopping-bag')"></i></div><span class="error-orbit error-orbit-one"></span><span class="error-orbit error-orbit-two"></span></div><div class="error-content"><span class="error-kicker">SHOPPILOT SUPPORT</span><h1>@yield('heading', 'Something went wrong')</h1><p>@yield('message', 'We could not complete your request. Please try again or return to the homepage.')</p><div class="error-actions">@yield('actions')</div><div class="error-help"><span><i class="fas fa-shield-alt"></i> Secure shopping</span><span><i class="fas fa-headset"></i> Support available</span><span><i class="fas fa-redo-alt"></i> Easy recovery</span></div></div></section><section class="error-quick"><a href="/shop"><span class="error-quick-icon"><i class="fas fa-shopping-bag"></i></span><span><strong>Shop Products</strong><small>Browse the latest products</small></span><i class="fas fa-chevron-right"></i></a><a href="/shop"><span class="error-quick-icon"><i class="fas fa-th-large"></i></span><span><strong>Browse Categories</strong><small>Find what you need</small></span><i class="fas fa-chevron-right"></i></a><a href="/contact"><span class="error-quick-icon"><i class="fas fa-envelope"></i></span><span><strong>Contact Us</strong><small>We are here to help</small></span><i class="fas fa-chevron-right"></i></a><a href="/track-order"><span class="error-quick-icon"><i class="fas fa-truck"></i></span><span><strong>Track Order</strong><small>Check delivery status</small></span><i class="fas fa-chevron-right"></i></a></section></div></main>
    <footer class="error-footer"><div class="error-container error-footer-inner"><div class="error-footer-brand"><span class="error-brand-mark"><i class="fas fa-shopping-bag"></i></span><div><strong>Shop<span>Pilot</span></strong><small>Shop Smart. Live Better</small></div></div><div class="error-footer-links"><a href="/">Home</a><a href="/shop">Shop</a><a href="/contact">Contact</a><a href="/faq">FAQ</a></div><p>© {{ date('Y') }} ShopPilot. All rights reserved.</p></div></footer>
</body>
</html>
