@extends('layouts.admin')

@section('meta_title', 'Newsletter Subscribers')

@section('page_content')
<div class="row align-items-center justify-content-between mb-3"><div class="col-12 col-md-auto"><h4 class="font-weight-bold mb-0"><i class="fas fa-envelope-open-text text-primary mr-2"></i> Newsletter Subscribers</h4><small class="text-muted">Manage frontend newsletter subscriptions without leaving the page.</small></div><div class="col-12 col-md-auto mt-2 mt-md-0 d-flex"><button type="button" class="btn btn-primary btn-sm mr-2" id="btnCreateNewsletterSubscriber"><i class="fas fa-plus mr-1"></i> Add Subscriber</button><a href="{{ route('admin.newsletter-subscribers.trash') }}" class="btn btn-outline-danger btn-sm"><i class="fas fa-trash-alt mr-1"></i> Trash Bin</a></div></div>
<div class="row mb-3"><div class="col-6 col-lg-3 mb-2 mb-lg-0"><div class="small-box bg-info mb-0"><div class="inner"><h3 id="newsletterStatTotal">{{ $stats['total'] }}</h3><p>Total</p></div><div class="icon"><i class="fas fa-users"></i></div></div></div><div class="col-6 col-lg-3 mb-2 mb-lg-0"><div class="small-box bg-success mb-0"><div class="inner"><h3 id="newsletterStatSubscribed">{{ $stats['subscribed'] }}</h3><p>Subscribed</p></div><div class="icon"><i class="fas fa-user-check"></i></div></div></div><div class="col-6 col-lg-3"><div class="small-box bg-secondary mb-0"><div class="inner"><h3 id="newsletterStatUnsubscribed">{{ $stats['unsubscribed'] }}</h3><p>Unsubscribed</p></div><div class="icon"><i class="fas fa-user-slash"></i></div></div></div><div class="col-6 col-lg-3"><div class="small-box bg-danger mb-0"><div class="inner"><h3 id="newsletterStatTrash">{{ $stats['trash'] }}</h3><p>Trash</p></div><div class="icon"><i class="fas fa-trash"></i></div></div></div></div>
<div class="card card-outline card-primary shadow-sm"><div class="card-header bg-white"><form id="newsletterSubscriberFilterForm" method="GET" action="{{ route('admin.newsletter-subscribers.index') }}" class="form-row align-items-end"><div class="col-lg-7 col-md-6 mb-2 mb-md-0"><label class="small text-muted font-weight-bold">Search</label><input type="search" name="search" value="{{ $filters['search'] ?? '' }}" class="form-control form-control-sm" placeholder="Search subscriber email..."></div><div class="col-lg-3 col-md-3 mb-2 mb-md-0"><label class="small text-muted font-weight-bold">Status</label><select name="status" class="custom-select custom-select-sm"><option value="">All Statuses</option><option value="subscribed" @selected(($filters['status'] ?? '') === 'subscribed')>Subscribed</option><option value="unsubscribed" @selected(($filters['status'] ?? '') === 'unsubscribed')>Unsubscribed</option></select></div><div class="col-lg-2 col-md-3 text-md-right"><button type="button" id="btnResetNewsletterSubscriberFilter" class="btn btn-light border btn-sm btn-block"><i class="fas fa-redo-alt mr-1"></i> Reset</button></div></form></div><form id="newsletterSubscriberBulkForm" method="POST" action="{{ route('admin.newsletter-subscribers.bulk-action') }}">@csrf<div class="card-body border-bottom py-2"><div class="d-flex align-items-center flex-wrap"><select name="action" class="custom-select custom-select-sm mr-2 mb-1" style="width: 220px;"><option value="">Bulk Actions</option>@can('newsletter-subscribers.update')<option value="subscribe">Mark Subscribed</option><option value="unsubscribe">Mark Unsubscribed</option>@endcan @can('newsletter-subscribers.delete')<option value="delete">Move to Trash</option>@endcan</select><button type="submit" class="btn btn-primary btn-sm mb-1"><i class="fas fa-check mr-1"></i> Apply</button></div></div></form><div class="card-body p-0 position-relative"><div id="newsletterSubscriberTableOverlay" class="overlay d-none"><i class="fas fa-2x fa-sync-alt fa-spin"></i></div><div id="newsletterSubscriberTableContainer">@include('backoffice.admin.newsletter-subscribers.partials.table', ['subscribers' => $subscribers, 'isTrash' => false])</div></div><div class="card-footer bg-white border-top py-2" id="newsletterSubscriberPaginationContainer">@if($subscribers->hasPages()){{ $subscribers->links() }}@endif</div></div>
@include('backoffice.admin.newsletter-subscribers.partials.form')
@include('backoffice.admin.newsletter-subscribers.partials.show')
@endsection

@push('js')
@include('backoffice.admin.newsletter-subscribers.partials.script', ['fetchUrl' => route('admin.newsletter-subscribers.index'), 'isTrashPage' => false])
@endpush
