<script>
$(function(){
    const fetchUrl=@json($fetchUrl); let pending=null; let timer=null;
    function reload(url=fetchUrl){ $('#customerTableOverlay').removeClass('d-none'); $.get(url,$('#customerFilterForm').serialize()).done(r=>{$('#customerTableContainer').html(r.html);$('#customerPagination').html(r.pagination);}).fail(()=>showAlert('Failed to load customers.','danger')).always(()=>$('#customerTableOverlay').addClass('d-none')); }
    $('#customer-search').on('input',function(){clearTimeout(timer);timer=setTimeout(()=>reload(),350)}); $('#customer-filter-status').on('change',()=>reload()); $('#btnResetCustomerFilter').on('click',function(){$('#customerFilterForm')[0].reset();reload()});
    $(document).on('click','#customerPagination a.page-link',function(e){e.preventDefault();reload($(this).attr('href'))});
    $(document).on('change','[data-select-all]',function(){const t=$(this).data('selectAll');$(`${t} [data-row-checkbox]`).prop('checked',$(this).is(':checked'))});
    function errorsClear(){$('.invalid-feedback').text('');$('#customerAjaxForm .is-invalid').removeClass('is-invalid')}
    $('#btnCreateCustomer').on('click',function(){errorsClear();$('#customerAjaxForm')[0].reset();$('#customerFormMethod').val('POST');$('#customerAjaxForm').attr('action',@json(route('admin.customers.store')));$('#customerFormTitle').text('Create Customer');$('.customer-pwd-required').removeClass('d-none');$('#customerPwdHint').addClass('d-none');$('#customer-password,#customer-password-confirmation').prop('required',true);$('#customerFormModal').modal('show')});
    $(document).on('click','.btn-edit-customer',function(){const id=$(this).data('id');errorsClear();$.get(`/admin/customers/${id}/edit`).done(r=>{const c=r.customer;$('#customerAjaxForm')[0].reset();$('#customerFormMethod').val('PUT');$('#customerAjaxForm').attr('action',`/admin/customers/${id}`);$('#customerFormTitle').text('Update Customer: '+c.name);$('#customer-name').val(c.name);$('#customer-email').val(c.email);$('#customer-status').val(c.status);$('.customer-pwd-required').addClass('d-none');$('#customerPwdHint').removeClass('d-none');$('#customer-password,#customer-password-confirmation').prop('required',false);$('#customerFormModal').modal('show')}).fail(()=>showAlert('Could not load customer.','danger'))});
    $('#customerAjaxForm').on('submit',function(e){e.preventDefault();errorsClear();const f=$(this),b=$('#btnSubmitCustomer');b.prop('disabled',true);$.ajax({url:f.attr('action'),method:'POST',data:f.serialize(),dataType:'json'}).done(r=>{$('#customerFormModal').modal('hide');showAlert(r.message);reload()}).fail(x=>{if(x.status===422){Object.entries(x.responseJSON.errors||{}).forEach(([k,v])=>{$('#err-'+k.replace('.','_')).text(v[0]);$(`[name="${k}"]`).addClass('is-invalid')})}else showAlert(x.responseJSON?.message||'Save failed.','danger')}).always(()=>b.prop('disabled',false))});
    $(document).on('click','.btn-view-customer',function(){const id=$(this).data('id');$.get(`/admin/customers/${id}`).done(r=>{const c=r.customer;$('#show-customer-avatar').text(c.name.charAt(0).toUpperCase());$('#show-customer-name').text(c.name);$('#show-customer-email').text(c.email);$('#show-customer-status').html(`<span class="badge badge-${c.status==='Active'?'success':'secondary'}">${c.status}</span>`);$('#show-customer-orders').text(c.orders_count);$('#show-customer-created').text(c.created_at);$('#customerShowModal').modal('show')})});
    $(document).on('click','.btn-customer-action',function(){pending={url:$(this).data('url'),method:$(this).data('method'),data:{_token:@json(csrf_token())}};$('#customerConfirmTitle').text($(this).data('title'));$('#customerConfirmText').text($(this).data('text'));$('#customerConfirmModal').modal('show')});
    $('#customerBulkForm').on('submit',function(e){e.preventDefault();const action=$(this).find('[name=action]').val();const ids=$('[data-row-checkbox]:checked').map(function(){return $(this).val()}).get();if(!action||!ids.length){showAlert('Select customers and a bulk action.','danger');return}pending={url:$(this).attr('action'),method:'POST',data:{_token:@json(csrf_token()),action:action,customer_ids:ids}};$('#customerConfirmTitle').text('Confirm Bulk Action');$('#customerConfirmText').text('Process '+ids.length+' selected customer(s)?');$('#customerConfirmModal').modal('show')});
    $('#customerConfirmButton').on('click',function(){if(!pending)return;const b=$(this);b.prop('disabled',true);$.ajax({url:pending.url,method:pending.method,data:pending.data,dataType:'json'}).done(r=>{$('#customerConfirmModal').modal('hide');showAlert(r.message);reload()}).fail(x=>{$('#customerConfirmModal').modal('hide');showAlert(x.responseJSON?.message||'Action failed.','danger')}).always(()=>{b.prop('disabled',false);pending=null})});
});
</script>
