<script>
$(function () {
    const fetchUrl = @json($fetchUrl);
    const isTrashPage = @json((bool) ($isTrashPage ?? false));
    const storeUrl = @json(route('admin.newsletter-subscribers.store'));
    const csrfToken = @json(csrf_token());
    let searchTimeout = null;

    function updateStats(stats) { if (!stats) return; $('#newsletterStatTotal').text(stats.total ?? 0); $('#newsletterStatSubscribed').text(stats.subscribed ?? 0); $('#newsletterStatUnsubscribed').text(stats.unsubscribed ?? 0); $('#newsletterStatTrash').text(stats.trash ?? 0); }
    function reloadNewsletterSubscriberTable(url = fetchUrl) { $('#newsletterSubscriberTableOverlay').removeClass('d-none'); $.ajax({url: url, method: 'GET', data: $('#newsletterSubscriberFilterForm').serialize(), dataType: 'json', success: function (res) { $('#newsletterSubscriberTableContainer').html(res.html || ''); $('#newsletterSubscriberPaginationContainer').html(res.pagination || ''); updateStats(res.stats); }, error: function (xhr) { showAlert(xhr.responseJSON?.message || 'Failed to refresh newsletter subscribers.', 'error'); }, complete: function () { $('#newsletterSubscriberTableOverlay').addClass('d-none'); $('#newsletterSubscriberSelectAll').prop('checked', false); }}); }
    function clearFormErrors() { $('#newsletterSubscriberAjaxForm .is-invalid').removeClass('is-invalid'); $('#newsletterSubscriberAjaxForm .ajax-validation-error').remove(); }
    function showValidationErrors(errors) { clearFormErrors(); Object.entries(errors || {}).forEach(([key, messages]) => { const field = document.getElementsByName(key)[0]; if (!field) return; $(field).addClass('is-invalid'); $('<div>', {class: 'invalid-feedback d-block ajax-validation-error', text: Array.isArray(messages) ? messages[0] : String(messages)}).insertAfter(field); }); }
    function resetForm() { const form = $('#newsletterSubscriberAjaxForm')[0]; if (!form) return; form.reset(); clearFormErrors(); $('#newsletterSubscriberFormMethod').val('POST'); $('#newsletterSubscriberAjaxForm').attr('action', storeUrl); $('#newsletterSubscriberFormModalTitle span').text('Add Newsletter Subscriber'); $('#newsletter-subscriber-status').val('subscribed'); }
    function populateForm(subscriber, updateUrl) { resetForm(); $('#newsletterSubscriberFormMethod').val('PUT'); $('#newsletterSubscriberAjaxForm').attr('action', updateUrl); $('#newsletterSubscriberFormModalTitle span').text('Update Newsletter Subscriber'); $('#newsletter-subscriber-email').val(subscriber.email || ''); $('#newsletter-subscriber-status').val(subscriber.status || 'subscribed'); }
    function populateShow(subscriber) { $('#showNewsletterSubscriberEmail').attr('href', subscriber.email ? `mailto:${subscriber.email}` : '#').text(subscriber.email || '—'); $('#showNewsletterSubscriberStatus').removeClass('badge-success badge-secondary').addClass(subscriber.status === 'subscribed' ? 'badge-success' : 'badge-secondary').text(subscriber.status ? subscriber.status.charAt(0).toUpperCase() + subscriber.status.slice(1) : '—'); $('#showNewsletterSubscriberSubscribed').text(subscriber.subscribed_at || '—'); $('#showNewsletterSubscriberUnsubscribed').text(subscriber.unsubscribed_at || '—'); $('#showNewsletterSubscriberUpdated').text(subscriber.updated_at || '—'); }

    $('#newsletterSubscriberFilterForm input[name="search"]').on('input', function () { clearTimeout(searchTimeout); searchTimeout = setTimeout(() => reloadNewsletterSubscriberTable(), 350); });
    $('#newsletterSubscriberFilterForm select[name="status"]').on('change', function () { reloadNewsletterSubscriberTable(); });
    $('#btnResetNewsletterSubscriberFilter').on('click', function () { $('#newsletterSubscriberFilterForm')[0]?.reset(); reloadNewsletterSubscriberTable(); });
    $(document).on('click', '#newsletterSubscriberPaginationContainer a.page-link', function (event) { event.preventDefault(); const url = $(this).attr('href'); if (url) reloadNewsletterSubscriberTable(url); });
    $(document).on('change', '#newsletterSubscriberSelectAll', function () { $('[data-newsletter-subscriber-checkbox]').prop('checked', this.checked); });
    $('#btnCreateNewsletterSubscriber').on('click', function () { resetForm(); $('#newsletterSubscriberFormModal').modal('show'); });

    $(document).on('click', '.btn-view-newsletter-subscriber', function (event) { event.preventDefault(); $.ajax({url: $(this).data('url'), method: 'GET', dataType: 'json', success: function (res) { if (!res.success) return; populateShow(res.subscriber); $('#newsletterSubscriberShowModal').modal('show'); }, error: function (xhr) { showAlert(xhr.responseJSON?.message || 'Could not load subscriber details.', 'error'); }}); });
    $(document).on('click', '.btn-edit-newsletter-subscriber', function (event) { event.preventDefault(); const button = $(this); $.ajax({url: button.data('url'), method: 'GET', dataType: 'json', success: function (res) { if (!res.success) return; populateForm(res.subscriber, button.data('update-url')); $('#newsletterSubscriberFormModal').modal('show'); }, error: function (xhr) { showAlert(xhr.responseJSON?.message || 'Could not load subscriber for editing.', 'error'); }}); });

    $(document).off('submit.newsletterSubscriber', '#newsletterSubscriberAjaxForm').on('submit.newsletterSubscriber', '#newsletterSubscriberAjaxForm', function (event) { event.preventDefault(); clearFormErrors(); const form = $(this); const button = $('#btnSubmitNewsletterSubscriber'); const original = button.html(); button.prop('disabled', true).html('<i class="fas fa-spinner fa-spin mr-1"></i> Saving...'); $.ajax({url: form.attr('action'), method: 'POST', data: form.serialize(), dataType: 'json', success: function (res) { $('#newsletterSubscriberFormModal').modal('hide'); showAlert(res.message || 'Subscriber saved successfully.', 'success'); reloadNewsletterSubscriberTable(); }, error: function (xhr) { if (xhr.status === 422) { showValidationErrors(xhr.responseJSON?.errors || {}); showAlert('Please fix the highlighted fields.', 'error'); return; } showAlert(xhr.responseJSON?.message || 'Could not save subscriber.', 'error'); }, complete: function () { button.prop('disabled', false).html(original); }}); });

    function executeAction(button) { $.ajax({url: button.data('url'), method: button.data('method') || 'POST', data: {_token: csrfToken}, dataType: 'json', success: function (res) { showAlert(res.message || 'Operation completed successfully.', 'success'); reloadNewsletterSubscriberTable(); }, error: function (xhr) { showAlert(xhr.responseJSON?.message || 'Operation failed.', 'error'); }}); }
    $(document).on('click', '.btn-newsletter-subscriber-action', function (event) { event.preventDefault(); const button = $(this); const execute = () => executeAction(button); if (!window.Swal || typeof window.Swal.fire !== 'function') { if (window.confirm(button.data('confirm-text') || 'Continue?')) execute(); return; } window.Swal.fire({title: button.data('confirm-title') || 'Are you sure?', text: button.data('confirm-text') || 'Please confirm this action.', type: 'warning', showCancelButton: true, confirmButtonColor: '#dc3545', confirmButtonText: 'Yes, continue', cancelButtonText: 'Cancel'}).then(function (result) { if (result.value || result.isConfirmed) execute(); }); });

    $(document).off('submit.newsletterSubscriberBulk', '#newsletterSubscriberBulkForm').on('submit.newsletterSubscriberBulk', '#newsletterSubscriberBulkForm', function (event) { event.preventDefault(); const form = $(this); const action = form.find('[name="action"]').val(); const ids = $('[data-newsletter-subscriber-checkbox]:checked').map(function () { return this.value; }).get(); if (!action || !ids.length) { showAlert('Please select subscribers and a bulk action.', 'error'); return; } const run = function () { $.ajax({url: form.attr('action'), method: 'POST', data: form.serialize() + '&' + $.param({subscriber_ids: ids}), dataType: 'json', success: function (res) { showAlert(res.message || 'Subscribers processed.', 'success'); reloadNewsletterSubscriberTable(); }, error: function (xhr) { showAlert(xhr.responseJSON?.message || 'Bulk action failed.', 'error'); }}); }; if (!window.Swal || typeof window.Swal.fire !== 'function') { if (window.confirm('Process selected newsletter subscribers?')) run(); return; } window.Swal.fire({title: 'Confirm bulk action', text: `${ids.length} newsletter subscriber(s) will be processed.`, type: action === 'force-delete' ? 'warning' : 'question', showCancelButton: true, confirmButtonText: 'Yes, continue'}).then(function (result) { if (result.value || result.isConfirmed) run(); }); });

    if (!isTrashPage) { const query = new URLSearchParams(window.location.search); const showId = Number(query.get('show') || 0); const editId = Number(query.get('edit') || 0); if (showId > 0) $(`.btn-view-newsletter-subscriber[data-url$="/${showId}"]`).first().trigger('click'); if (editId > 0) $(`.btn-edit-newsletter-subscriber[data-update-url$="/${editId}"]`).first().trigger('click'); }
});
</script>
